/**
 * Typed accessors over src/data/blogIndex.json — the lightweight published-post
 * index (no `content`/`faqs`/SEO bodies) generated by scripts/generate-blog-index.ts.
 *
 * List surfaces (the /blog listing, related-article cards, transformation-story
 * cross-links) import THIS module instead of `@/data/blogPosts`, so only the
 * blog post page itself (`BlogPostContainer`) bundles the ~400KB full dataset.
 */
import blogIndexJson from "./blogIndex.json";

export interface BlogIndexEntry {
  id: string;
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  tags: string[];
  readTime: string;
  date: string;
  author: string;
  featuredImage?: string;
  isoDate?: string;
  timestamp: number;
}

const blogIndex = blogIndexJson as BlogIndexEntry[];

// Returns the shared module-level array — treat it as read-only. Use
// spread/filter/map to derive; never sort or splice it in place.
export const getBlogIndex = (): BlogIndexEntry[] => blogIndex;

export const getBlogIndexEntryBySlug = (
  slug: string
): BlogIndexEntry | undefined => blogIndex.find((entry) => entry.slug === slug);

export const getBlogIndexCategories = (): string[] =>
  Array.from(new Set(blogIndex.map((entry) => entry.category)));

export const getBlogIndexEntryDateTime = (
  entry: BlogIndexEntry
): string | undefined =>
  entry.isoDate ? `${entry.isoDate}T00:00:00.000Z` : undefined;
