import type { FeaturedReview } from '@/data/featuredReviews';

/**
 * Generated by scripts/import-demandforce-reviews.mjs.
 *
 * The Demand Force export has not been provided yet, so this intentionally
 * remains empty. Do not add review totals or aggregate-rating claims until a
 * source export is imported and reviewed.
 */
export const demandForceReviews: FeaturedReview[] = [];
